// Code generated by MockGen. DO NOT EDIT.
// dev-11 fix: adicionados métodos de invalidação de cache
package mocks

import (
	"context"
	"reflect"

	"github.com/rafapasa/mcp-server-openerp/internal/dto"
	"github.com/rafapasa/mcp-server-openerp/internal/llm"
	"github.com/rafapasa/mcp-server-openerp/internal/models"
	"go.uber.org/mock/gomock"
)

type MockCardapioServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCardapioServiceInterfaceMockRecorder
}

type MockCardapioServiceInterfaceMockRecorder struct {
	mock *MockCardapioServiceInterface
}

func NewMockCardapioServiceInterface(ctrl *gomock.Controller) *MockCardapioServiceInterface {
	mock := &MockCardapioServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCardapioServiceInterfaceMockRecorder{mock}
	return mock
}

func (m *MockCardapioServiceInterface) EXPECT() *MockCardapioServiceInterfaceMockRecorder {
	return m.recorder
}

func (m *MockCardapioServiceInterface) GetCardapio(ctx context.Context, tenantID uint) ([]dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardapio", ctx, tenantID)
	ret0, _ := ret[0].([]dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardapioServiceInterfaceMockRecorder) GetCardapio(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardapio", reflect.TypeOf((*MockCardapioServiceInterface)(nil).GetCardapio), ctx, tenantID)
}

func (m *MockCardapioServiceInterface) BuscarProdutoPorNome(ctx context.Context, tenantID, nome string) (*dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutoPorNome", ctx, tenantID, nome)
	ret0, _ := ret[0].(*dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardapioServiceInterfaceMockRecorder) BuscarProdutoPorNome(ctx, tenantID, nome interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutoPorNome", reflect.TypeOf((*MockCardapioServiceInterface)(nil).BuscarProdutoPorNome), ctx, tenantID, nome)
}

func (m *MockCardapioServiceInterface) BuscarProdutoPorIdNoCardapio(cardapio []dto.ProdutoItem, produtoID uint) (*dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutoPorIdNoCardapio", cardapio, produtoID)
	ret0, _ := ret[0].(*dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardapioServiceInterfaceMockRecorder) BuscarProdutoPorIdNoCardapio(cardapio, produtoID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutoPorIdNoCardapio", reflect.TypeOf((*MockCardapioServiceInterface)(nil).BuscarProdutoPorIdNoCardapio), cardapio, produtoID)
}

func (m *MockCardapioServiceInterface) ItemExisteNoCardapio(cardapio []dto.ProdutoItem, nome string) (*dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ItemExisteNoCardapio", cardapio, nome)
	ret0, _ := ret[0].(*dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardapioServiceInterfaceMockRecorder) ItemExisteNoCardapio(cardapio, nome interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemExisteNoCardapio", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ItemExisteNoCardapio), cardapio, nome)
}

func (m *MockCardapioServiceInterface) EncontrarItemSimilar(cardapio []dto.ProdutoItem, nome string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncontrarItemSimilar", cardapio, nome)
	ret0, _ := ret[0].(string)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) EncontrarItemSimilar(cardapio, nome interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncontrarItemSimilar", reflect.TypeOf((*MockCardapioServiceInterface)(nil).EncontrarItemSimilar), cardapio, nome)
}

func (m *MockCardapioServiceInterface) FormatarCardapio(cardapio []dto.ProdutoItem) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatarCardapio", cardapio)
	ret0, _ := ret[0].(string)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) FormatarCardapio(cardapio interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatarCardapio", reflect.TypeOf((*MockCardapioServiceInterface)(nil).FormatarCardapio), cardapio)
}

func (m *MockCardapioServiceInterface) ListarCategoriasHumanizado(cardapio []dto.ProdutoItem) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListarCategoriasHumanizado", cardapio)
	ret0, _ := ret[0].(string)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) ListarCategoriasHumanizado(cardapio interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListarCategoriasHumanizado", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ListarCategoriasHumanizado), cardapio)
}

func (m *MockCardapioServiceInterface) ListarProdutosHumanizado(cardapio []dto.ProdutoItem, filtro string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListarProdutosHumanizado", cardapio, filtro)
	ret0, _ := ret[0].(string)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) ListarProdutosHumanizado(cardapio, filtro interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListarProdutosHumanizado", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ListarProdutosHumanizado), cardapio, filtro)
}

func (m *MockCardapioServiceInterface) ListWithFilters(ctx context.Context, tenantID uint, categoriaID *uint, disponivel *bool, nome string, page, limit int) ([]dto.ProdutoDTO, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithFilters", ctx, tenantID, categoriaID, disponivel, nome, page, limit)
	ret0, _ := ret[0].([]dto.ProdutoDTO)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (mr *MockCardapioServiceInterfaceMockRecorder) ListWithFilters(ctx, tenantID, categoriaID, disponivel, nome, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithFilters", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ListWithFilters), ctx, tenantID, categoriaID, disponivel, nome, page, limit)
}

func (m *MockCardapioServiceInterface) FindByID(ctx context.Context, id uint) (*dto.ProdutoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*dto.ProdutoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardapioServiceInterfaceMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCardapioServiceInterface)(nil).FindByID), ctx, id)
}

func (m *MockCardapioServiceInterface) ReduzirPorKeywords(ctx context.Context, tenantID uint, keywords []llm.LLMKeywordItemResult) ([]dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReduzirPorKeywords", ctx, tenantID, keywords)
	ret0, _ := ret[0].([]dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCardapioServiceInterfaceMockRecorder) ReduzirPorKeywords(ctx, tenantID, keywords interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReduzirPorKeywords", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ReduzirPorKeywords), ctx, tenantID, keywords)
}

// === NOVO dev-11 ===
func (m *MockCardapioServiceInterface) InvalidateCache(ctx context.Context, tenantID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateCache", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) InvalidateCache(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateCache", reflect.TypeOf((*MockCardapioServiceInterface)(nil).InvalidateCache), ctx, tenantID)
}

func (m *MockCardapioServiceInterface) Create(ctx context.Context, produto *models.Produto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, produto)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) Create(ctx, produto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCardapioServiceInterface)(nil).Create), ctx, produto)
}

func (m *MockCardapioServiceInterface) Update(ctx context.Context, produto *models.Produto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, produto)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) Update(ctx, produto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCardapioServiceInterface)(nil).Update), ctx, produto)
}

func (m *MockCardapioServiceInterface) Delete(ctx context.Context, id uint, tenantID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) Delete(ctx, id, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCardapioServiceInterface)(nil).Delete), ctx, id, tenantID)
}

func (m *MockCardapioServiceInterface) UpdateDisponibilidade(ctx context.Context, id uint, tenantID uint, disponivel bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDisponibilidade", ctx, id, tenantID, disponivel)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCardapioServiceInterfaceMockRecorder) UpdateDisponibilidade(ctx, id, tenantID, disponivel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDisponibilidade", reflect.TypeOf((*MockCardapioServiceInterface)(nil).UpdateDisponibilidade), ctx, id, tenantID, disponivel)
}
