// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/service (interfaces: CardapioServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/cardapio_service_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/service CardapioServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/rafapasa/mcp-server-openerp/internal/dto"
	llm "github.com/rafapasa/mcp-server-openerp/internal/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockCardapioServiceInterface is a mock of CardapioServiceInterface interface.
type MockCardapioServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCardapioServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockCardapioServiceInterfaceMockRecorder is the mock recorder for MockCardapioServiceInterface.
type MockCardapioServiceInterfaceMockRecorder struct {
	mock *MockCardapioServiceInterface
}

// NewMockCardapioServiceInterface creates a new mock instance.
func NewMockCardapioServiceInterface(ctrl *gomock.Controller) *MockCardapioServiceInterface {
	mock := &MockCardapioServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCardapioServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardapioServiceInterface) EXPECT() *MockCardapioServiceInterfaceMockRecorder {
	return m.recorder
}

// BuscarProdutoPorIdNoCardapio mocks base method.
func (m *MockCardapioServiceInterface) BuscarProdutoPorIdNoCardapio(cardapio []dto.ProdutoItem, produtoID uint) (*dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutoPorIdNoCardapio", cardapio, produtoID)
	ret0, _ := ret[0].(*dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutoPorIdNoCardapio indicates an expected call of BuscarProdutoPorIdNoCardapio.
func (mr *MockCardapioServiceInterfaceMockRecorder) BuscarProdutoPorIdNoCardapio(cardapio, produtoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutoPorIdNoCardapio", reflect.TypeOf((*MockCardapioServiceInterface)(nil).BuscarProdutoPorIdNoCardapio), cardapio, produtoID)
}

// BuscarProdutoPorNome mocks base method.
func (m *MockCardapioServiceInterface) BuscarProdutoPorNome(ctx context.Context, tenantID, nome string) (*dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutoPorNome", ctx, tenantID, nome)
	ret0, _ := ret[0].(*dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutoPorNome indicates an expected call of BuscarProdutoPorNome.
func (mr *MockCardapioServiceInterfaceMockRecorder) BuscarProdutoPorNome(ctx, tenantID, nome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutoPorNome", reflect.TypeOf((*MockCardapioServiceInterface)(nil).BuscarProdutoPorNome), ctx, tenantID, nome)
}

// EncontrarItemSimilar mocks base method.
func (m *MockCardapioServiceInterface) EncontrarItemSimilar(cardapio []dto.ProdutoItem, nome string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncontrarItemSimilar", cardapio, nome)
	ret0, _ := ret[0].(string)
	return ret0
}

// EncontrarItemSimilar indicates an expected call of EncontrarItemSimilar.
func (mr *MockCardapioServiceInterfaceMockRecorder) EncontrarItemSimilar(cardapio, nome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncontrarItemSimilar", reflect.TypeOf((*MockCardapioServiceInterface)(nil).EncontrarItemSimilar), cardapio, nome)
}

// FindByID mocks base method.
func (m *MockCardapioServiceInterface) FindByID(ctx context.Context, id uint) (*dto.ProdutoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*dto.ProdutoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCardapioServiceInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCardapioServiceInterface)(nil).FindByID), ctx, id)
}

// FormatarCardapio mocks base method.
func (m *MockCardapioServiceInterface) FormatarCardapio(cardapio []dto.ProdutoItem) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatarCardapio", cardapio)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatarCardapio indicates an expected call of FormatarCardapio.
func (mr *MockCardapioServiceInterfaceMockRecorder) FormatarCardapio(cardapio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatarCardapio", reflect.TypeOf((*MockCardapioServiceInterface)(nil).FormatarCardapio), cardapio)
}

// GetCardapio mocks base method.
func (m *MockCardapioServiceInterface) GetCardapio(ctx context.Context, tenantID uint) ([]dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCardapio", ctx, tenantID)
	ret0, _ := ret[0].([]dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCardapio indicates an expected call of GetCardapio.
func (mr *MockCardapioServiceInterfaceMockRecorder) GetCardapio(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCardapio", reflect.TypeOf((*MockCardapioServiceInterface)(nil).GetCardapio), ctx, tenantID)
}

// ItemExisteNoCardapio mocks base method.
func (m *MockCardapioServiceInterface) ItemExisteNoCardapio(cardapio []dto.ProdutoItem, nome string) (*dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ItemExisteNoCardapio", cardapio, nome)
	ret0, _ := ret[0].(*dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ItemExisteNoCardapio indicates an expected call of ItemExisteNoCardapio.
func (mr *MockCardapioServiceInterfaceMockRecorder) ItemExisteNoCardapio(cardapio, nome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemExisteNoCardapio", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ItemExisteNoCardapio), cardapio, nome)
}

// ListWithFilters mocks base method.
func (m *MockCardapioServiceInterface) ListWithFilters(ctx context.Context, tenantID uint, categoriaID *uint, disponivel *bool, nome string, page, limit int) ([]dto.ProdutoDTO, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithFilters", ctx, tenantID, categoriaID, disponivel, nome, page, limit)
	ret0, _ := ret[0].([]dto.ProdutoDTO)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWithFilters indicates an expected call of ListWithFilters.
func (mr *MockCardapioServiceInterfaceMockRecorder) ListWithFilters(ctx, tenantID, categoriaID, disponivel, nome, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithFilters", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ListWithFilters), ctx, tenantID, categoriaID, disponivel, nome, page, limit)
}

// ListarCategoriasHumanizado mocks base method.
func (m *MockCardapioServiceInterface) ListarCategoriasHumanizado(cardapio []dto.ProdutoItem) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListarCategoriasHumanizado", cardapio)
	ret0, _ := ret[0].(string)
	return ret0
}

// ListarCategoriasHumanizado indicates an expected call of ListarCategoriasHumanizado.
func (mr *MockCardapioServiceInterfaceMockRecorder) ListarCategoriasHumanizado(cardapio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListarCategoriasHumanizado", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ListarCategoriasHumanizado), cardapio)
}

// ListarProdutosHumanizado mocks base method.
func (m *MockCardapioServiceInterface) ListarProdutosHumanizado(cardapio []dto.ProdutoItem, filtro string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListarProdutosHumanizado", cardapio, filtro)
	ret0, _ := ret[0].(string)
	return ret0
}

// ListarProdutosHumanizado indicates an expected call of ListarProdutosHumanizado.
func (mr *MockCardapioServiceInterfaceMockRecorder) ListarProdutosHumanizado(cardapio, filtro any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListarProdutosHumanizado", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ListarProdutosHumanizado), cardapio, filtro)
}

// ReduzirPorKeywords mocks base method.
func (m *MockCardapioServiceInterface) ReduzirPorKeywords(ctx context.Context, tenantID uint, keywords []llm.LLMKeywordItemResult) ([]dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReduzirPorKeywords", ctx, tenantID, keywords)
	ret0, _ := ret[0].([]dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReduzirPorKeywords indicates an expected call of ReduzirPorKeywords.
func (mr *MockCardapioServiceInterfaceMockRecorder) ReduzirPorKeywords(ctx, tenantID, keywords any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReduzirPorKeywords", reflect.TypeOf((*MockCardapioServiceInterface)(nil).ReduzirPorKeywords), ctx, tenantID, keywords)
}
