// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/repository (interfaces: ClienteRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/cliente_repo_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/repository ClienteRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/rafapasa/mcp-server-openerp/internal/models"
	repository "github.com/rafapasa/mcp-server-openerp/internal/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockClienteRepositoryInterface is a mock of ClienteRepositoryInterface interface.
type MockClienteRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClienteRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockClienteRepositoryInterfaceMockRecorder is the mock recorder for MockClienteRepositoryInterface.
type MockClienteRepositoryInterfaceMockRecorder struct {
	mock *MockClienteRepositoryInterface
}

// NewMockClienteRepositoryInterface creates a new mock instance.
func NewMockClienteRepositoryInterface(ctrl *gomock.Controller) *MockClienteRepositoryInterface {
	mock := &MockClienteRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockClienteRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClienteRepositoryInterface) EXPECT() *MockClienteRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountByStatus mocks base method.
func (m *MockClienteRepositoryInterface) CountByStatus(ctx context.Context, tenantID, status string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByStatus", ctx, tenantID, status)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByStatus indicates an expected call of CountByStatus.
func (mr *MockClienteRepositoryInterfaceMockRecorder) CountByStatus(ctx, tenantID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByStatus", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).CountByStatus), ctx, tenantID, status)
}

// CountByTenant mocks base method.
func (m *MockClienteRepositoryInterface) CountByTenant(ctx context.Context, tenantID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTenant", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTenant indicates an expected call of CountByTenant.
func (mr *MockClienteRepositoryInterfaceMockRecorder) CountByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTenant", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).CountByTenant), ctx, tenantID)
}

// Create mocks base method.
func (m *MockClienteRepositoryInterface) Create(ctx context.Context, cliente *models.Cliente) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cliente)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockClienteRepositoryInterfaceMockRecorder) Create(ctx, cliente any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).Create), ctx, cliente)
}

// Delete mocks base method.
func (m *MockClienteRepositoryInterface) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClienteRepositoryInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockClienteRepositoryInterface) FindByID(ctx context.Context, id uint) (*models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockClienteRepositoryInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).FindByID), ctx, id)
}

// FindByNome mocks base method.
func (m *MockClienteRepositoryInterface) FindByNome(ctx context.Context, tenantID, nome string) ([]models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNome", ctx, tenantID, nome)
	ret0, _ := ret[0].([]models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNome indicates an expected call of FindByNome.
func (mr *MockClienteRepositoryInterfaceMockRecorder) FindByNome(ctx, tenantID, nome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNome", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).FindByNome), ctx, tenantID, nome)
}

// FindByStatus mocks base method.
func (m *MockClienteRepositoryInterface) FindByStatus(ctx context.Context, tenantID, status string) ([]models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", ctx, tenantID, status)
	ret0, _ := ret[0].([]models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockClienteRepositoryInterfaceMockRecorder) FindByStatus(ctx, tenantID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).FindByStatus), ctx, tenantID, status)
}

// FindByTelefone mocks base method.
func (m *MockClienteRepositoryInterface) FindByTelefone(ctx context.Context, telefone string, tenantID uint) (*models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTelefone", ctx, telefone, tenantID)
	ret0, _ := ret[0].(*models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTelefone indicates an expected call of FindByTelefone.
func (mr *MockClienteRepositoryInterfaceMockRecorder) FindByTelefone(ctx, telefone, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTelefone", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).FindByTelefone), ctx, telefone, tenantID)
}

// FindByTenant mocks base method.
func (m *MockClienteRepositoryInterface) FindByTenant(ctx context.Context, tenantID string) ([]models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenant indicates an expected call of FindByTenant.
func (mr *MockClienteRepositoryInterfaceMockRecorder) FindByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenant", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).FindByTenant), ctx, tenantID)
}

// FindByUltimoPedidoAntes mocks base method.
func (m *MockClienteRepositoryInterface) FindByUltimoPedidoAntes(ctx context.Context, tenantID string, data time.Time) ([]models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUltimoPedidoAntes", ctx, tenantID, data)
	ret0, _ := ret[0].([]models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUltimoPedidoAntes indicates an expected call of FindByUltimoPedidoAntes.
func (mr *MockClienteRepositoryInterfaceMockRecorder) FindByUltimoPedidoAntes(ctx, tenantID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUltimoPedidoAntes", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).FindByUltimoPedidoAntes), ctx, tenantID, data)
}

// FindWithFilters mocks base method.
func (m *MockClienteRepositoryInterface) FindWithFilters(ctx context.Context, tenantID uint, nome, telefone string, limit, offset int) ([]models.Cliente, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilters", ctx, tenantID, nome, telefone, limit, offset)
	ret0, _ := ret[0].([]models.Cliente)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithFilters indicates an expected call of FindWithFilters.
func (mr *MockClienteRepositoryInterfaceMockRecorder) FindWithFilters(ctx, tenantID, nome, telefone, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilters", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).FindWithFilters), ctx, tenantID, nome, telefone, limit, offset)
}

// Update mocks base method.
func (m *MockClienteRepositoryInterface) Update(ctx context.Context, cliente *models.Cliente) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, cliente)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClienteRepositoryInterfaceMockRecorder) Update(ctx, cliente any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).Update), ctx, cliente)
}

// WithTx mocks base method.
func (m *MockClienteRepositoryInterface) WithTx(tx *gorm.DB) repository.ClienteRepositoryInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.ClienteRepositoryInterface)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockClienteRepositoryInterfaceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).WithTx), tx)
}
