// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/service (interfaces: ClienteServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/cliente_service_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/service ClienteServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/rafapasa/mcp-server-openerp/internal/dto"
	models "github.com/rafapasa/mcp-server-openerp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockClienteServiceInterface is a mock of ClienteServiceInterface interface.
type MockClienteServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClienteServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockClienteServiceInterfaceMockRecorder is the mock recorder for MockClienteServiceInterface.
type MockClienteServiceInterfaceMockRecorder struct {
	mock *MockClienteServiceInterface
}

// NewMockClienteServiceInterface creates a new mock instance.
func NewMockClienteServiceInterface(ctrl *gomock.Controller) *MockClienteServiceInterface {
	mock := &MockClienteServiceInterface{ctrl: ctrl}
	mock.recorder = &MockClienteServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClienteServiceInterface) EXPECT() *MockClienteServiceInterfaceMockRecorder {
	return m.recorder
}

// AdicionarEndereco mocks base method.
func (m *MockClienteServiceInterface) AdicionarEndereco(ctx context.Context, clienteID uint, req *dto.CriarEnderecoRequest) (*dto.EnderecoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdicionarEndereco", ctx, clienteID, req)
	ret0, _ := ret[0].(*dto.EnderecoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdicionarEndereco indicates an expected call of AdicionarEndereco.
func (mr *MockClienteServiceInterfaceMockRecorder) AdicionarEndereco(ctx, clienteID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdicionarEndereco", reflect.TypeOf((*MockClienteServiceInterface)(nil).AdicionarEndereco), ctx, clienteID, req)
}

// AtualizarDocumento mocks base method.
func (m *MockClienteServiceInterface) AtualizarDocumento(ctx context.Context, clienteID uint, inscricaoFederal string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarDocumento", ctx, clienteID, inscricaoFederal)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtualizarDocumento indicates an expected call of AtualizarDocumento.
func (mr *MockClienteServiceInterfaceMockRecorder) AtualizarDocumento(ctx, clienteID, inscricaoFederal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarDocumento", reflect.TypeOf((*MockClienteServiceInterface)(nil).AtualizarDocumento), ctx, clienteID, inscricaoFederal)
}

// AtualizarStatus mocks base method.
func (m *MockClienteServiceInterface) AtualizarStatus(ctx context.Context, clienteID uint, status, motivo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarStatus", ctx, clienteID, status, motivo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtualizarStatus indicates an expected call of AtualizarStatus.
func (mr *MockClienteServiceInterfaceMockRecorder) AtualizarStatus(ctx, clienteID, status, motivo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarStatus", reflect.TypeOf((*MockClienteServiceInterface)(nil).AtualizarStatus), ctx, clienteID, status, motivo)
}

// AtualizarUltimoPedido mocks base method.
func (m *MockClienteServiceInterface) AtualizarUltimoPedido(ctx context.Context, clienteID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarUltimoPedido", ctx, clienteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AtualizarUltimoPedido indicates an expected call of AtualizarUltimoPedido.
func (mr *MockClienteServiceInterfaceMockRecorder) AtualizarUltimoPedido(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarUltimoPedido", reflect.TypeOf((*MockClienteServiceInterface)(nil).AtualizarUltimoPedido), ctx, clienteID)
}

// BuscarInativos mocks base method.
func (m *MockClienteServiceInterface) BuscarInativos(ctx context.Context, tenantID uint, diasInatividade int) ([]dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarInativos", ctx, tenantID, diasInatividade)
	ret0, _ := ret[0].([]dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarInativos indicates an expected call of BuscarInativos.
func (mr *MockClienteServiceInterfaceMockRecorder) BuscarInativos(ctx, tenantID, diasInatividade any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarInativos", reflect.TypeOf((*MockClienteServiceInterface)(nil).BuscarInativos), ctx, tenantID, diasInatividade)
}

// BuscarOuCriarPorTelefone mocks base method.
func (m *MockClienteServiceInterface) BuscarOuCriarPorTelefone(ctx context.Context, tenantID uint, telefone, nomePerfil string) (*dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarOuCriarPorTelefone", ctx, tenantID, telefone, nomePerfil)
	ret0, _ := ret[0].(*dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarOuCriarPorTelefone indicates an expected call of BuscarOuCriarPorTelefone.
func (mr *MockClienteServiceInterfaceMockRecorder) BuscarOuCriarPorTelefone(ctx, tenantID, telefone, nomePerfil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarOuCriarPorTelefone", reflect.TypeOf((*MockClienteServiceInterface)(nil).BuscarOuCriarPorTelefone), ctx, tenantID, telefone, nomePerfil)
}

// BuscarPorNome mocks base method.
func (m *MockClienteServiceInterface) BuscarPorNome(ctx context.Context, tenantID uint, nome string) ([]dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarPorNome", ctx, tenantID, nome)
	ret0, _ := ret[0].([]dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarPorNome indicates an expected call of BuscarPorNome.
func (mr *MockClienteServiceInterfaceMockRecorder) BuscarPorNome(ctx, tenantID, nome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarPorNome", reflect.TypeOf((*MockClienteServiceInterface)(nil).BuscarPorNome), ctx, tenantID, nome)
}

// BuscarPorStatus mocks base method.
func (m *MockClienteServiceInterface) BuscarPorStatus(ctx context.Context, tenantID uint, status string) ([]dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarPorStatus", ctx, tenantID, status)
	ret0, _ := ret[0].([]dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarPorStatus indicates an expected call of BuscarPorStatus.
func (mr *MockClienteServiceInterfaceMockRecorder) BuscarPorStatus(ctx, tenantID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarPorStatus", reflect.TypeOf((*MockClienteServiceInterface)(nil).BuscarPorStatus), ctx, tenantID, status)
}

// ConverterParaDTO mocks base method.
func (m *MockClienteServiceInterface) ConverterParaDTO(cliente *models.Cliente) *dto.ClienteDTO {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConverterParaDTO", cliente)
	ret0, _ := ret[0].(*dto.ClienteDTO)
	return ret0
}

// ConverterParaDTO indicates an expected call of ConverterParaDTO.
func (mr *MockClienteServiceInterfaceMockRecorder) ConverterParaDTO(cliente any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConverterParaDTO", reflect.TypeOf((*MockClienteServiceInterface)(nil).ConverterParaDTO), cliente)
}

// CountByTenant mocks base method.
func (m *MockClienteServiceInterface) CountByTenant(ctx context.Context, tenantID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTenant", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTenant indicates an expected call of CountByTenant.
func (mr *MockClienteServiceInterfaceMockRecorder) CountByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTenant", reflect.TypeOf((*MockClienteServiceInterface)(nil).CountByTenant), ctx, tenantID)
}

// Create mocks base method.
func (m *MockClienteServiceInterface) Create(ctx context.Context, req *dto.CriarClienteRequest) (*dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClienteServiceInterfaceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClienteServiceInterface)(nil).Create), ctx, req)
}

// DefinirEnderecoPrincipal mocks base method.
func (m *MockClienteServiceInterface) DefinirEnderecoPrincipal(ctx context.Context, clienteID, enderecoID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefinirEnderecoPrincipal", ctx, clienteID, enderecoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DefinirEnderecoPrincipal indicates an expected call of DefinirEnderecoPrincipal.
func (mr *MockClienteServiceInterfaceMockRecorder) DefinirEnderecoPrincipal(ctx, clienteID, enderecoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefinirEnderecoPrincipal", reflect.TypeOf((*MockClienteServiceInterface)(nil).DefinirEnderecoPrincipal), ctx, clienteID, enderecoID)
}

// Delete mocks base method.
func (m *MockClienteServiceInterface) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClienteServiceInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClienteServiceInterface)(nil).Delete), ctx, id)
}

// FindByID mocks base method.
func (m *MockClienteServiceInterface) FindByID(ctx context.Context, id uint) (*dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockClienteServiceInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockClienteServiceInterface)(nil).FindByID), ctx, id)
}

// FindByTelefone mocks base method.
func (m *MockClienteServiceInterface) FindByTelefone(ctx context.Context, telefone string, tenantID uint) (*dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTelefone", ctx, telefone, tenantID)
	ret0, _ := ret[0].(*dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTelefone indicates an expected call of FindByTelefone.
func (mr *MockClienteServiceInterfaceMockRecorder) FindByTelefone(ctx, telefone, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTelefone", reflect.TypeOf((*MockClienteServiceInterface)(nil).FindByTelefone), ctx, telefone, tenantID)
}

// FindByTenant mocks base method.
func (m *MockClienteServiceInterface) FindByTenant(ctx context.Context, tenantID uint) ([]dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenant indicates an expected call of FindByTenant.
func (mr *MockClienteServiceInterfaceMockRecorder) FindByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenant", reflect.TypeOf((*MockClienteServiceInterface)(nil).FindByTenant), ctx, tenantID)
}

// GetStatus mocks base method.
func (m *MockClienteServiceInterface) GetStatus(ctx context.Context, clienteID uint) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, clienteID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockClienteServiceInterfaceMockRecorder) GetStatus(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockClienteServiceInterface)(nil).GetStatus), ctx, clienteID)
}

// InativarCliente mocks base method.
func (m *MockClienteServiceInterface) InativarCliente(ctx context.Context, clienteID uint, motivo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InativarCliente", ctx, clienteID, motivo)
	ret0, _ := ret[0].(error)
	return ret0
}

// InativarCliente indicates an expected call of InativarCliente.
func (mr *MockClienteServiceInterfaceMockRecorder) InativarCliente(ctx, clienteID, motivo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InativarCliente", reflect.TypeOf((*MockClienteServiceInterface)(nil).InativarCliente), ctx, clienteID, motivo)
}

// IsAtivo mocks base method.
func (m *MockClienteServiceInterface) IsAtivo(ctx context.Context, clienteID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAtivo", ctx, clienteID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAtivo indicates an expected call of IsAtivo.
func (mr *MockClienteServiceInterfaceMockRecorder) IsAtivo(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAtivo", reflect.TypeOf((*MockClienteServiceInterface)(nil).IsAtivo), ctx, clienteID)
}

// ListWithFilters mocks base method.
func (m *MockClienteServiceInterface) ListWithFilters(ctx context.Context, tenantID uint, nome, telefone string, page, limit int) ([]dto.ClienteDTO, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithFilters", ctx, tenantID, nome, telefone, page, limit)
	ret0, _ := ret[0].([]dto.ClienteDTO)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWithFilters indicates an expected call of ListWithFilters.
func (mr *MockClienteServiceInterfaceMockRecorder) ListWithFilters(ctx, tenantID, nome, telefone, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithFilters", reflect.TypeOf((*MockClienteServiceInterface)(nil).ListWithFilters), ctx, tenantID, nome, telefone, page, limit)
}

// ListarEnderecos mocks base method.
func (m *MockClienteServiceInterface) ListarEnderecos(ctx context.Context, clienteID uint) ([]dto.EnderecoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListarEnderecos", ctx, clienteID)
	ret0, _ := ret[0].([]dto.EnderecoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListarEnderecos indicates an expected call of ListarEnderecos.
func (mr *MockClienteServiceInterfaceMockRecorder) ListarEnderecos(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListarEnderecos", reflect.TypeOf((*MockClienteServiceInterface)(nil).ListarEnderecos), ctx, clienteID)
}

// ReativarCliente mocks base method.
func (m *MockClienteServiceInterface) ReativarCliente(ctx context.Context, clienteID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReativarCliente", ctx, clienteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReativarCliente indicates an expected call of ReativarCliente.
func (mr *MockClienteServiceInterfaceMockRecorder) ReativarCliente(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReativarCliente", reflect.TypeOf((*MockClienteServiceInterface)(nil).ReativarCliente), ctx, clienteID)
}

// RemoverEndereco mocks base method.
func (m *MockClienteServiceInterface) RemoverEndereco(ctx context.Context, clienteID, enderecoID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoverEndereco", ctx, clienteID, enderecoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoverEndereco indicates an expected call of RemoverEndereco.
func (mr *MockClienteServiceInterfaceMockRecorder) RemoverEndereco(ctx, clienteID, enderecoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoverEndereco", reflect.TypeOf((*MockClienteServiceInterface)(nil).RemoverEndereco), ctx, clienteID, enderecoID)
}

// Update mocks base method.
func (m *MockClienteServiceInterface) Update(ctx context.Context, id uint, req *dto.AtualizarClienteRequest) (*dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClienteServiceInterfaceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClienteServiceInterface)(nil).Update), ctx, id, req)
}

// ValidarCliente mocks base method.
func (m *MockClienteServiceInterface) ValidarCliente(ctx context.Context, clienteID uint) (*dto.ClienteDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidarCliente", ctx, clienteID)
	ret0, _ := ret[0].(*dto.ClienteDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidarCliente indicates an expected call of ValidarCliente.
func (mr *MockClienteServiceInterfaceMockRecorder) ValidarCliente(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidarCliente", reflect.TypeOf((*MockClienteServiceInterface)(nil).ValidarCliente), ctx, clienteID)
}

// ValidarDocumento mocks base method.
func (m *MockClienteServiceInterface) ValidarDocumento(inscricaoFederal string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidarDocumento", inscricaoFederal)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidarDocumento indicates an expected call of ValidarDocumento.
func (mr *MockClienteServiceInterfaceMockRecorder) ValidarDocumento(inscricaoFederal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidarDocumento", reflect.TypeOf((*MockClienteServiceInterface)(nil).ValidarDocumento), inscricaoFederal)
}
