// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/repository (interfaces: ClienteRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=cliente_repo_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/repository ClienteRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/rafapasa/mcp-server-openerp/internal/dto"
	models "github.com/rafapasa/mcp-server-openerp/internal/models"
	repository "github.com/rafapasa/mcp-server-openerp/internal/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockClienteRepositoryInterface is a mock of ClienteRepositoryInterface interface.
type MockClienteRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClienteRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockClienteRepositoryInterfaceMockRecorder is the mock recorder for MockClienteRepositoryInterface.
type MockClienteRepositoryInterfaceMockRecorder struct {
	mock *MockClienteRepositoryInterface
}

// NewMockClienteRepositoryInterface creates a new mock instance.
func NewMockClienteRepositoryInterface(ctrl *gomock.Controller) *MockClienteRepositoryInterface {
	mock := &MockClienteRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockClienteRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClienteRepositoryInterface) EXPECT() *MockClienteRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClienteRepositoryInterface) Create(ctx context.Context, req dto.CriarClienteRequest) (*models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClienteRepositoryInterfaceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockClienteRepositoryInterface) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClienteRepositoryInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).Delete), ctx, id)
}

// FindWithFilters mocks base method.
func (m *MockClienteRepositoryInterface) FindWithFilters(ctx context.Context, limit, offset int, filters map[string]any) ([]models.Cliente, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilters", ctx, limit, offset, filters)
	ret0, _ := ret[0].([]models.Cliente)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithFilters indicates an expected call of FindWithFilters.
func (mr *MockClienteRepositoryInterfaceMockRecorder) FindWithFilters(ctx, limit, offset, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilters", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).FindWithFilters), ctx, limit, offset, filters)
}

// GetByEmail mocks base method.
func (m *MockClienteRepositoryInterface) GetByEmail(ctx context.Context, tenantId uint, email string) (*models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, tenantId, email)
	ret0, _ := ret[0].(*models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockClienteRepositoryInterfaceMockRecorder) GetByEmail(ctx, tenantId, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).GetByEmail), ctx, tenantId, email)
}

// GetByID mocks base method.
func (m *MockClienteRepositoryInterface) GetByID(ctx context.Context, id uint) (*models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockClienteRepositoryInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).GetByID), ctx, id)
}

// GetByInscricaoFederal mocks base method.
func (m *MockClienteRepositoryInterface) GetByInscricaoFederal(ctx context.Context, tenantId uint, inscricaoFederal string) (*models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInscricaoFederal", ctx, tenantId, inscricaoFederal)
	ret0, _ := ret[0].(*models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInscricaoFederal indicates an expected call of GetByInscricaoFederal.
func (mr *MockClienteRepositoryInterfaceMockRecorder) GetByInscricaoFederal(ctx, tenantId, inscricaoFederal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInscricaoFederal", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).GetByInscricaoFederal), ctx, tenantId, inscricaoFederal)
}

// GetByTelefone mocks base method.
func (m *MockClienteRepositoryInterface) GetByTelefone(ctx context.Context, tenantId uint, telefone string) (*models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTelefone", ctx, tenantId, telefone)
	ret0, _ := ret[0].(*models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTelefone indicates an expected call of GetByTelefone.
func (mr *MockClienteRepositoryInterfaceMockRecorder) GetByTelefone(ctx, tenantId, telefone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTelefone", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).GetByTelefone), ctx, tenantId, telefone)
}

// Update mocks base method.
func (m *MockClienteRepositoryInterface) Update(ctx context.Context, id uint, req dto.AtualizarClienteRequest) (*models.Cliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*models.Cliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClienteRepositoryInterfaceMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).Update), ctx, id, req)
}

// WithTx mocks base method.
func (m *MockClienteRepositoryInterface) WithTx(tx *gorm.DB) repository.ClienteRepositoryInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.ClienteRepositoryInterface)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockClienteRepositoryInterfaceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockClienteRepositoryInterface)(nil).WithTx), tx)
}
