// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/repository (interfaces: EnderecoRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/endereco_repo_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/repository EnderecoRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/rafapasa/mcp-server-openerp/internal/models"
	repository "github.com/rafapasa/mcp-server-openerp/internal/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockEnderecoRepositoryInterface is a mock of EnderecoRepositoryInterface interface.
type MockEnderecoRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEnderecoRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockEnderecoRepositoryInterfaceMockRecorder is the mock recorder for MockEnderecoRepositoryInterface.
type MockEnderecoRepositoryInterfaceMockRecorder struct {
	mock *MockEnderecoRepositoryInterface
}

// NewMockEnderecoRepositoryInterface creates a new mock instance.
func NewMockEnderecoRepositoryInterface(ctrl *gomock.Controller) *MockEnderecoRepositoryInterface {
	mock := &MockEnderecoRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockEnderecoRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnderecoRepositoryInterface) EXPECT() *MockEnderecoRepositoryInterfaceMockRecorder {
	return m.recorder
}

// CountAtivosByCliente mocks base method.
func (m *MockEnderecoRepositoryInterface) CountAtivosByCliente(ctx context.Context, clienteID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAtivosByCliente", ctx, clienteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAtivosByCliente indicates an expected call of CountAtivosByCliente.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) CountAtivosByCliente(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAtivosByCliente", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).CountAtivosByCliente), ctx, clienteID)
}

// CountByCliente mocks base method.
func (m *MockEnderecoRepositoryInterface) CountByCliente(ctx context.Context, clienteID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCliente", ctx, clienteID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCliente indicates an expected call of CountByCliente.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) CountByCliente(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCliente", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).CountByCliente), ctx, clienteID)
}

// Create mocks base method.
func (m *MockEnderecoRepositoryInterface) Create(ctx context.Context, endereco *models.Endereco) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, endereco)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) Create(ctx, endereco any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).Create), ctx, endereco)
}

// Delete mocks base method.
func (m *MockEnderecoRepositoryInterface) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).Delete), ctx, id)
}

// DeletePermanente mocks base method.
func (m *MockEnderecoRepositoryInterface) DeletePermanente(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePermanente", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePermanente indicates an expected call of DeletePermanente.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) DeletePermanente(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePermanente", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).DeletePermanente), ctx, id)
}

// FindByCEP mocks base method.
func (m *MockEnderecoRepositoryInterface) FindByCEP(ctx context.Context, cep string) ([]models.Endereco, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCEP", ctx, cep)
	ret0, _ := ret[0].([]models.Endereco)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCEP indicates an expected call of FindByCEP.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) FindByCEP(ctx, cep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCEP", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).FindByCEP), ctx, cep)
}

// FindByCliente mocks base method.
func (m *MockEnderecoRepositoryInterface) FindByCliente(ctx context.Context, clienteID uint) ([]models.Endereco, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCliente", ctx, clienteID)
	ret0, _ := ret[0].([]models.Endereco)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCliente indicates an expected call of FindByCliente.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) FindByCliente(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCliente", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).FindByCliente), ctx, clienteID)
}

// FindByClienteAtivos mocks base method.
func (m *MockEnderecoRepositoryInterface) FindByClienteAtivos(ctx context.Context, clienteID uint) ([]models.Endereco, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByClienteAtivos", ctx, clienteID)
	ret0, _ := ret[0].([]models.Endereco)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByClienteAtivos indicates an expected call of FindByClienteAtivos.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) FindByClienteAtivos(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByClienteAtivos", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).FindByClienteAtivos), ctx, clienteID)
}

// FindByClienteETipo mocks base method.
func (m *MockEnderecoRepositoryInterface) FindByClienteETipo(ctx context.Context, clienteID uint, tipo string) ([]models.Endereco, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByClienteETipo", ctx, clienteID, tipo)
	ret0, _ := ret[0].([]models.Endereco)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByClienteETipo indicates an expected call of FindByClienteETipo.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) FindByClienteETipo(ctx, clienteID, tipo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByClienteETipo", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).FindByClienteETipo), ctx, clienteID, tipo)
}

// FindByID mocks base method.
func (m *MockEnderecoRepositoryInterface) FindByID(ctx context.Context, id uint) (*models.Endereco, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Endereco)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).FindByID), ctx, id)
}

// FindPrincipal mocks base method.
func (m *MockEnderecoRepositoryInterface) FindPrincipal(ctx context.Context, clienteID uint) (*models.Endereco, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPrincipal", ctx, clienteID)
	ret0, _ := ret[0].(*models.Endereco)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPrincipal indicates an expected call of FindPrincipal.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) FindPrincipal(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPrincipal", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).FindPrincipal), ctx, clienteID)
}

// UnsetPrincipalByCliente mocks base method.
func (m *MockEnderecoRepositoryInterface) UnsetPrincipalByCliente(ctx context.Context, clienteID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsetPrincipalByCliente", ctx, clienteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsetPrincipalByCliente indicates an expected call of UnsetPrincipalByCliente.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) UnsetPrincipalByCliente(ctx, clienteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsetPrincipalByCliente", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).UnsetPrincipalByCliente), ctx, clienteID)
}

// Update mocks base method.
func (m *MockEnderecoRepositoryInterface) Update(ctx context.Context, endereco *models.Endereco) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, endereco)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) Update(ctx, endereco any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).Update), ctx, endereco)
}

// WithTx mocks base method.
func (m *MockEnderecoRepositoryInterface) WithTx(tx *gorm.DB) repository.EnderecoRepositoryInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.EnderecoRepositoryInterface)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockEnderecoRepositoryInterfaceMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockEnderecoRepositoryInterface)(nil).WithTx), tx)
}
