// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/service (interfaces: LLMServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/llm_service_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/service LLMServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/rafapasa/mcp-server-openerp/internal/dto"
	llm "github.com/rafapasa/mcp-server-openerp/internal/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMServiceInterface is a mock of LLMServiceInterface interface.
type MockLLMServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLLMServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockLLMServiceInterfaceMockRecorder is the mock recorder for MockLLMServiceInterface.
type MockLLMServiceInterfaceMockRecorder struct {
	mock *MockLLMServiceInterface
}

// NewMockLLMServiceInterface creates a new mock instance.
func NewMockLLMServiceInterface(ctrl *gomock.Controller) *MockLLMServiceInterface {
	mock := &MockLLMServiceInterface{ctrl: ctrl}
	mock.recorder = &MockLLMServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMServiceInterface) EXPECT() *MockLLMServiceInterfaceMockRecorder {
	return m.recorder
}

// ClassificarEExtrairKeywords mocks base method.
func (m *MockLLMServiceInterface) ClassificarEExtrairKeywords(ctx context.Context, tenantID uint, textoHigienizado, contextoCarrinho string) (*llm.IntencaoEKeywordsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClassificarEExtrairKeywords", ctx, tenantID, textoHigienizado, contextoCarrinho)
	ret0, _ := ret[0].(*llm.IntencaoEKeywordsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClassificarEExtrairKeywords indicates an expected call of ClassificarEExtrairKeywords.
func (mr *MockLLMServiceInterfaceMockRecorder) ClassificarEExtrairKeywords(ctx, tenantID, textoHigienizado, contextoCarrinho any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClassificarEExtrairKeywords", reflect.TypeOf((*MockLLMServiceInterface)(nil).ClassificarEExtrairKeywords), ctx, tenantID, textoHigienizado, contextoCarrinho)
}

// GetProviderInfo mocks base method.
func (m *MockLLMServiceInterface) GetProviderInfo() (string, string, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProviderInfo")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	return ret0, ret1, ret2
}

// GetProviderInfo indicates an expected call of GetProviderInfo.
func (mr *MockLLMServiceInterfaceMockRecorder) GetProviderInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProviderInfo", reflect.TypeOf((*MockLLMServiceInterface)(nil).GetProviderInfo))
}

// HasValidConfig mocks base method.
func (m *MockLLMServiceInterface) HasValidConfig() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasValidConfig")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasValidConfig indicates an expected call of HasValidConfig.
func (mr *MockLLMServiceInterfaceMockRecorder) HasValidConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasValidConfig", reflect.TypeOf((*MockLLMServiceInterface)(nil).HasValidConfig))
}

// IsOnline mocks base method.
func (m *MockLLMServiceInterface) IsOnline(ctx context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOnline", ctx)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsOnline indicates an expected call of IsOnline.
func (mr *MockLLMServiceInterfaceMockRecorder) IsOnline(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOnline", reflect.TypeOf((*MockLLMServiceInterface)(nil).IsOnline), ctx)
}

// ObterTextoBase mocks base method.
func (m *MockLLMServiceInterface) ObterTextoBase(ctx context.Context, tenantID uint, input dto.MessageInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObterTextoBase", ctx, tenantID, input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ObterTextoBase indicates an expected call of ObterTextoBase.
func (mr *MockLLMServiceInterfaceMockRecorder) ObterTextoBase(ctx, tenantID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObterTextoBase", reflect.TypeOf((*MockLLMServiceInterface)(nil).ObterTextoBase), ctx, tenantID, input)
}

// ResolveItemsByMenu mocks base method.
func (m *MockLLMServiceInterface) ResolveItemsByMenu(ctx context.Context, tenantID uint, input dto.MessageInput, cardapio []dto.ProdutoItem) (*dto.IntencaoCliente, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveItemsByMenu", ctx, tenantID, input, cardapio)
	ret0, _ := ret[0].(*dto.IntencaoCliente)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveItemsByMenu indicates an expected call of ResolveItemsByMenu.
func (mr *MockLLMServiceInterfaceMockRecorder) ResolveItemsByMenu(ctx, tenantID, input, cardapio any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveItemsByMenu", reflect.TypeOf((*MockLLMServiceInterface)(nil).ResolveItemsByMenu), ctx, tenantID, input, cardapio)
}

// ResolverItensByKeyWords mocks base method.
func (m *MockLLMServiceInterface) ResolverItensByKeyWords(ctx context.Context, tenantID uint, keywords []llm.LLMKeywordItemResult, cardapioReduzido []dto.ProdutoItem) ([]dto.ItemCarrinho, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolverItensByKeyWords", ctx, tenantID, keywords, cardapioReduzido)
	ret0, _ := ret[0].([]dto.ItemCarrinho)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolverItensByKeyWords indicates an expected call of ResolverItensByKeyWords.
func (mr *MockLLMServiceInterfaceMockRecorder) ResolverItensByKeyWords(ctx, tenantID, keywords, cardapioReduzido any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolverItensByKeyWords", reflect.TypeOf((*MockLLMServiceInterface)(nil).ResolverItensByKeyWords), ctx, tenantID, keywords, cardapioReduzido)
}
