// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/service (interfaces: PedidoServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/pedido_service_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/service PedidoServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/rafapasa/mcp-server-openerp/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockPedidoServiceInterface is a mock of PedidoServiceInterface interface.
type MockPedidoServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPedidoServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPedidoServiceInterfaceMockRecorder is the mock recorder for MockPedidoServiceInterface.
type MockPedidoServiceInterfaceMockRecorder struct {
	mock *MockPedidoServiceInterface
}

// NewMockPedidoServiceInterface creates a new mock instance.
func NewMockPedidoServiceInterface(ctrl *gomock.Controller) *MockPedidoServiceInterface {
	mock := &MockPedidoServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPedidoServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPedidoServiceInterface) EXPECT() *MockPedidoServiceInterfaceMockRecorder {
	return m.recorder
}

// AtualizarStatusPedido mocks base method.
func (m *MockPedidoServiceInterface) AtualizarStatusPedido(ctx context.Context, id uint, status string) (*dto.PedidoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AtualizarStatusPedido", ctx, id, status)
	ret0, _ := ret[0].(*dto.PedidoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AtualizarStatusPedido indicates an expected call of AtualizarStatusPedido.
func (mr *MockPedidoServiceInterfaceMockRecorder) AtualizarStatusPedido(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AtualizarStatusPedido", reflect.TypeOf((*MockPedidoServiceInterface)(nil).AtualizarStatusPedido), ctx, id, status)
}

// CountPedidosHoje mocks base method.
func (m *MockPedidoServiceInterface) CountPedidosHoje(ctx context.Context, tenantID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPedidosHoje", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPedidosHoje indicates an expected call of CountPedidosHoje.
func (mr *MockPedidoServiceInterfaceMockRecorder) CountPedidosHoje(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPedidosHoje", reflect.TypeOf((*MockPedidoServiceInterface)(nil).CountPedidosHoje), ctx, tenantID)
}

// CountPedidosSemana mocks base method.
func (m *MockPedidoServiceInterface) CountPedidosSemana(ctx context.Context, tenantID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPedidosSemana", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPedidosSemana indicates an expected call of CountPedidosSemana.
func (mr *MockPedidoServiceInterfaceMockRecorder) CountPedidosSemana(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPedidosSemana", reflect.TypeOf((*MockPedidoServiceInterface)(nil).CountPedidosSemana), ctx, tenantID)
}

// CountPendentes mocks base method.
func (m *MockPedidoServiceInterface) CountPendentes(ctx context.Context, tenantID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPendentes", ctx, tenantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPendentes indicates an expected call of CountPendentes.
func (mr *MockPedidoServiceInterfaceMockRecorder) CountPendentes(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPendentes", reflect.TypeOf((*MockPedidoServiceInterface)(nil).CountPendentes), ctx, tenantID)
}

// CountPorStatus mocks base method.
func (m *MockPedidoServiceInterface) CountPorStatus(ctx context.Context, tenantID uint) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPorStatus", ctx, tenantID)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPorStatus indicates an expected call of CountPorStatus.
func (mr *MockPedidoServiceInterfaceMockRecorder) CountPorStatus(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPorStatus", reflect.TypeOf((*MockPedidoServiceInterface)(nil).CountPorStatus), ctx, tenantID)
}

// Create mocks base method.
func (m *MockPedidoServiceInterface) Create(ctx context.Context, req *dto.CriarPedidoRequest) (*dto.PedidoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.PedidoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPedidoServiceInterfaceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPedidoServiceInterface)(nil).Create), ctx, req)
}

// FaturamentoHoje mocks base method.
func (m *MockPedidoServiceInterface) FaturamentoHoje(ctx context.Context, tenantID uint) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FaturamentoHoje", ctx, tenantID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FaturamentoHoje indicates an expected call of FaturamentoHoje.
func (mr *MockPedidoServiceInterfaceMockRecorder) FaturamentoHoje(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FaturamentoHoje", reflect.TypeOf((*MockPedidoServiceInterface)(nil).FaturamentoHoje), ctx, tenantID)
}

// FaturamentoMes mocks base method.
func (m *MockPedidoServiceInterface) FaturamentoMes(ctx context.Context, tenantID uint) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FaturamentoMes", ctx, tenantID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FaturamentoMes indicates an expected call of FaturamentoMes.
func (mr *MockPedidoServiceInterfaceMockRecorder) FaturamentoMes(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FaturamentoMes", reflect.TypeOf((*MockPedidoServiceInterface)(nil).FaturamentoMes), ctx, tenantID)
}

// FindByID mocks base method.
func (m *MockPedidoServiceInterface) FindByID(ctx context.Context, id uint) (*dto.PedidoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*dto.PedidoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPedidoServiceInterfaceMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPedidoServiceInterface)(nil).FindByID), ctx, id)
}

// FindByTenant mocks base method.
func (m *MockPedidoServiceInterface) FindByTenant(ctx context.Context, tenantID uint) ([]dto.PedidoDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]dto.PedidoDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenant indicates an expected call of FindByTenant.
func (mr *MockPedidoServiceInterfaceMockRecorder) FindByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenant", reflect.TypeOf((*MockPedidoServiceInterface)(nil).FindByTenant), ctx, tenantID)
}

// ListByCliente mocks base method.
func (m *MockPedidoServiceInterface) ListByCliente(ctx context.Context, clienteID uint, page, limit int) ([]dto.PedidoDTO, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCliente", ctx, clienteID, page, limit)
	ret0, _ := ret[0].([]dto.PedidoDTO)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByCliente indicates an expected call of ListByCliente.
func (mr *MockPedidoServiceInterfaceMockRecorder) ListByCliente(ctx, clienteID, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCliente", reflect.TypeOf((*MockPedidoServiceInterface)(nil).ListByCliente), ctx, clienteID, page, limit)
}

// ListWithFilters mocks base method.
func (m *MockPedidoServiceInterface) ListWithFilters(ctx context.Context, tenantID, clienteID uint, status string, dataInicio, dataFim time.Time, page, limit int) ([]dto.PedidoDTO, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithFilters", ctx, tenantID, clienteID, status, dataInicio, dataFim, page, limit)
	ret0, _ := ret[0].([]dto.PedidoDTO)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWithFilters indicates an expected call of ListWithFilters.
func (mr *MockPedidoServiceInterfaceMockRecorder) ListWithFilters(ctx, tenantID, clienteID, status, dataInicio, dataFim, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithFilters", reflect.TypeOf((*MockPedidoServiceInterface)(nil).ListWithFilters), ctx, tenantID, clienteID, status, dataInicio, dataFim, page, limit)
}

// ProcessarPedido mocks base method.
func (m *MockPedidoServiceInterface) ProcessarPedido(ctx context.Context, tenantID, clienteID uint, clienteNome string, pedidoExtraido *dto.PedidoExtraido) (*dto.PedidoConfirmado, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessarPedido", ctx, tenantID, clienteID, clienteNome, pedidoExtraido)
	ret0, _ := ret[0].(*dto.PedidoConfirmado)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessarPedido indicates an expected call of ProcessarPedido.
func (mr *MockPedidoServiceInterfaceMockRecorder) ProcessarPedido(ctx, tenantID, clienteID, clienteNome, pedidoExtraido any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessarPedido", reflect.TypeOf((*MockPedidoServiceInterface)(nil).ProcessarPedido), ctx, tenantID, clienteID, clienteNome, pedidoExtraido)
}
