// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/repository (interfaces: ProdutoRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/produto_repo_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/repository ProdutoRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/rafapasa/mcp-server-openerp/internal/dto"
	models "github.com/rafapasa/mcp-server-openerp/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProdutoRepository is a mock of ProdutoRepository interface.
type MockProdutoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProdutoRepositoryMockRecorder
	isgomock struct{}
}

// MockProdutoRepositoryMockRecorder is the mock recorder for MockProdutoRepository.
type MockProdutoRepositoryMockRecorder struct {
	mock *MockProdutoRepository
}

// NewMockProdutoRepository creates a new mock instance.
func NewMockProdutoRepository(ctrl *gomock.Controller) *MockProdutoRepository {
	mock := &MockProdutoRepository{ctrl: ctrl}
	mock.recorder = &MockProdutoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProdutoRepository) EXPECT() *MockProdutoRepositoryMockRecorder {
	return m.recorder
}

// BuscarProdutosLote mocks base method.
func (m *MockProdutoRepository) BuscarProdutosLote(ctx context.Context, tenantID string, nomes []string) (map[string]dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutosLote", ctx, tenantID, nomes)
	ret0, _ := ret[0].(map[string]dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutosLote indicates an expected call of BuscarProdutosLote.
func (mr *MockProdutoRepositoryMockRecorder) BuscarProdutosLote(ctx, tenantID, nomes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutosLote", reflect.TypeOf((*MockProdutoRepository)(nil).BuscarProdutosLote), ctx, tenantID, nomes)
}

// BuscarProdutosPorNome mocks base method.
func (m *MockProdutoRepository) BuscarProdutosPorNome(ctx context.Context, tenantID, nome string, limit int) ([]dto.ProdutoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuscarProdutosPorNome", ctx, tenantID, nome, limit)
	ret0, _ := ret[0].([]dto.ProdutoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuscarProdutosPorNome indicates an expected call of BuscarProdutosPorNome.
func (mr *MockProdutoRepositoryMockRecorder) BuscarProdutosPorNome(ctx, tenantID, nome, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuscarProdutosPorNome", reflect.TypeOf((*MockProdutoRepository)(nil).BuscarProdutosPorNome), ctx, tenantID, nome, limit)
}

// Create mocks base method.
func (m *MockProdutoRepository) Create(ctx context.Context, produto *models.Produto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, produto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockProdutoRepositoryMockRecorder) Create(ctx, produto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProdutoRepository)(nil).Create), ctx, produto)
}

// Delete mocks base method.
func (m *MockProdutoRepository) Delete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProdutoRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProdutoRepository)(nil).Delete), ctx, id)
}

// FindByCategoria mocks base method.
func (m *MockProdutoRepository) FindByCategoria(ctx context.Context, tenantID, categoriaID uint) ([]models.Produto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCategoria", ctx, tenantID, categoriaID)
	ret0, _ := ret[0].([]models.Produto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCategoria indicates an expected call of FindByCategoria.
func (mr *MockProdutoRepositoryMockRecorder) FindByCategoria(ctx, tenantID, categoriaID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCategoria", reflect.TypeOf((*MockProdutoRepository)(nil).FindByCategoria), ctx, tenantID, categoriaID)
}

// FindByID mocks base method.
func (m *MockProdutoRepository) FindByID(ctx context.Context, id uint) (*models.Produto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*models.Produto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockProdutoRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockProdutoRepository)(nil).FindByID), ctx, id)
}

// FindByNome mocks base method.
func (m *MockProdutoRepository) FindByNome(ctx context.Context, tenantID uint, nome string) (*models.Produto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNome", ctx, tenantID, nome)
	ret0, _ := ret[0].(*models.Produto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByNome indicates an expected call of FindByNome.
func (mr *MockProdutoRepositoryMockRecorder) FindByNome(ctx, tenantID, nome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNome", reflect.TypeOf((*MockProdutoRepository)(nil).FindByNome), ctx, tenantID, nome)
}

// FindByTenant mocks base method.
func (m *MockProdutoRepository) FindByTenant(ctx context.Context, tenantID uint) ([]models.Produto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]models.Produto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenant indicates an expected call of FindByTenant.
func (mr *MockProdutoRepositoryMockRecorder) FindByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenant", reflect.TypeOf((*MockProdutoRepository)(nil).FindByTenant), ctx, tenantID)
}

// FindByTenantDisponiveis mocks base method.
func (m *MockProdutoRepository) FindByTenantDisponiveis(ctx context.Context, tenantID uint) ([]models.Produto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTenantDisponiveis", ctx, tenantID)
	ret0, _ := ret[0].([]models.Produto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTenantDisponiveis indicates an expected call of FindByTenantDisponiveis.
func (mr *MockProdutoRepositoryMockRecorder) FindByTenantDisponiveis(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTenantDisponiveis", reflect.TypeOf((*MockProdutoRepository)(nil).FindByTenantDisponiveis), ctx, tenantID)
}

// FindWithFilters mocks base method.
func (m *MockProdutoRepository) FindWithFilters(ctx context.Context, tenantID uint, categoriaID *uint, disponivel *bool, nome string, limit, offset int) ([]models.Produto, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWithFilters", ctx, tenantID, categoriaID, disponivel, nome, limit, offset)
	ret0, _ := ret[0].([]models.Produto)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindWithFilters indicates an expected call of FindWithFilters.
func (mr *MockProdutoRepositoryMockRecorder) FindWithFilters(ctx, tenantID, categoriaID, disponivel, nome, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWithFilters", reflect.TypeOf((*MockProdutoRepository)(nil).FindWithFilters), ctx, tenantID, categoriaID, disponivel, nome, limit, offset)
}

// Update mocks base method.
func (m *MockProdutoRepository) Update(ctx context.Context, produto *models.Produto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, produto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProdutoRepositoryMockRecorder) Update(ctx, produto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProdutoRepository)(nil).Update), ctx, produto)
}
