// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/database (interfaces: RedisInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/redis_interface_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/database RedisInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	database "github.com/rafapasa/mcp-server-openerp/internal/database"
	redis "github.com/redis/go-redis/v9"
	gomock "go.uber.org/mock/gomock"
)

// MockRedisInterface is a mock of RedisInterface interface.
type MockRedisInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRedisInterfaceMockRecorder
	isgomock struct{}
}

// MockRedisInterfaceMockRecorder is the mock recorder for MockRedisInterface.
type MockRedisInterfaceMockRecorder struct {
	mock *MockRedisInterface
}

// NewMockRedisInterface creates a new mock instance.
func NewMockRedisInterface(ctrl *gomock.Controller) *MockRedisInterface {
	mock := &MockRedisInterface{ctrl: ctrl}
	mock.recorder = &MockRedisInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisInterface) EXPECT() *MockRedisInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedisInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedisInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedisInterface)(nil).Close))
}

// Delete mocks base method.
func (m *MockRedisInterface) Delete(keys ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range keys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRedisInterfaceMockRecorder) Delete(keys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRedisInterface)(nil).Delete), keys...)
}

// DeleteWithContext mocks base method.
func (m *MockRedisInterface) DeleteWithContext(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithContext", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWithContext indicates an expected call of DeleteWithContext.
func (mr *MockRedisInterfaceMockRecorder) DeleteWithContext(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithContext", reflect.TypeOf((*MockRedisInterface)(nil).DeleteWithContext), ctx, key)
}

// Exists mocks base method.
func (m *MockRedisInterface) Exists(key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockRedisInterfaceMockRecorder) Exists(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockRedisInterface)(nil).Exists), key)
}

// Expire mocks base method.
func (m *MockRedisInterface) Expire(key string, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expire", key, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Expire indicates an expected call of Expire.
func (mr *MockRedisInterfaceMockRecorder) Expire(key, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expire", reflect.TypeOf((*MockRedisInterface)(nil).Expire), key, expiration)
}

// Get mocks base method.
func (m *MockRedisInterface) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRedisInterfaceMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRedisInterface)(nil).Get), key)
}

// GetClient mocks base method.
func (m *MockRedisInterface) GetClient() *redis.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(*redis.Client)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockRedisInterfaceMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockRedisInterface)(nil).GetClient))
}

// GetJSON mocks base method.
func (m *MockRedisInterface) GetJSON(key string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSON", key, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetJSON indicates an expected call of GetJSON.
func (mr *MockRedisInterfaceMockRecorder) GetJSON(key, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSON", reflect.TypeOf((*MockRedisInterface)(nil).GetJSON), key, dest)
}

// GetJSONWithContext mocks base method.
func (m *MockRedisInterface) GetJSONWithContext(ctx context.Context, key string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJSONWithContext", ctx, key, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetJSONWithContext indicates an expected call of GetJSONWithContext.
func (mr *MockRedisInterfaceMockRecorder) GetJSONWithContext(ctx, key, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJSONWithContext", reflect.TypeOf((*MockRedisInterface)(nil).GetJSONWithContext), ctx, key, dest)
}

// GetWithContext mocks base method.
func (m *MockRedisInterface) GetWithContext(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithContext", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithContext indicates an expected call of GetWithContext.
func (mr *MockRedisInterfaceMockRecorder) GetWithContext(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithContext", reflect.TypeOf((*MockRedisInterface)(nil).GetWithContext), ctx, key)
}

// InvalidateByTenant mocks base method.
func (m *MockRedisInterface) InvalidateByTenant(ctx context.Context, pattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateByTenant", ctx, pattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateByTenant indicates an expected call of InvalidateByTenant.
func (mr *MockRedisInterfaceMockRecorder) InvalidateByTenant(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateByTenant", reflect.TypeOf((*MockRedisInterface)(nil).InvalidateByTenant), ctx, pattern)
}

// IsConnected mocks base method.
func (m *MockRedisInterface) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockRedisInterfaceMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockRedisInterface)(nil).IsConnected))
}

// Ping mocks base method.
func (m *MockRedisInterface) Ping() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping")
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRedisInterfaceMockRecorder) Ping() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRedisInterface)(nil).Ping))
}

// Set mocks base method.
func (m *MockRedisInterface) Set(key string, value any, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockRedisInterfaceMockRecorder) Set(key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRedisInterface)(nil).Set), key, value, expiration)
}

// SetJSON mocks base method.
func (m *MockRedisInterface) SetJSON(key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJSON", key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJSON indicates an expected call of SetJSON.
func (mr *MockRedisInterfaceMockRecorder) SetJSON(key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJSON", reflect.TypeOf((*MockRedisInterface)(nil).SetJSON), key, value, ttl)
}

// SetJSONWithContext mocks base method.
func (m *MockRedisInterface) SetJSONWithContext(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetJSONWithContext", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetJSONWithContext indicates an expected call of SetJSONWithContext.
func (mr *MockRedisInterfaceMockRecorder) SetJSONWithContext(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJSONWithContext", reflect.TypeOf((*MockRedisInterface)(nil).SetJSONWithContext), ctx, key, value, ttl)
}

// SetNXWithContext mocks base method.
func (m *MockRedisInterface) SetNXWithContext(ctx context.Context, key string, value any, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNXWithContext", ctx, key, value, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetNXWithContext indicates an expected call of SetNXWithContext.
func (mr *MockRedisInterfaceMockRecorder) SetNXWithContext(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNXWithContext", reflect.TypeOf((*MockRedisInterface)(nil).SetNXWithContext), ctx, key, value, ttl)
}

// SetWithContext mocks base method.
func (m *MockRedisInterface) SetWithContext(ctx context.Context, key string, value any, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWithContext", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWithContext indicates an expected call of SetWithContext.
func (mr *MockRedisInterfaceMockRecorder) SetWithContext(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWithContext", reflect.TypeOf((*MockRedisInterface)(nil).SetWithContext), ctx, key, value, ttl)
}

// WithContext mocks base method.
func (m *MockRedisInterface) WithContext(ctx context.Context) database.RedisInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithContext", ctx)
	ret0, _ := ret[0].(database.RedisInterface)
	return ret0
}

// WithContext indicates an expected call of WithContext.
func (mr *MockRedisInterfaceMockRecorder) WithContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithContext", reflect.TypeOf((*MockRedisInterface)(nil).WithContext), ctx)
}
