// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafapasa/mcp-server-openerp/internal/service (interfaces: TenantServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/tenant_service_mock.go -package=mocks github.com/rafapasa/mcp-server-openerp/internal/service TenantServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/rafapasa/mcp-server-openerp/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockTenantServiceInterface is a mock of TenantServiceInterface interface.
type MockTenantServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTenantServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTenantServiceInterfaceMockRecorder is the mock recorder for MockTenantServiceInterface.
type MockTenantServiceInterfaceMockRecorder struct {
	mock *MockTenantServiceInterface
}

// NewMockTenantServiceInterface creates a new mock instance.
func NewMockTenantServiceInterface(ctrl *gomock.Controller) *MockTenantServiceInterface {
	mock := &MockTenantServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTenantServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantServiceInterface) EXPECT() *MockTenantServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantServiceInterface) Create(ctx context.Context, input dto.CreateTenantDTO) (*dto.TenantDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*dto.TenantDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTenantServiceInterfaceMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantServiceInterface)(nil).Create), ctx, input)
}

// GetByCNPJ mocks base method.
func (m *MockTenantServiceInterface) GetByCNPJ(ctx context.Context, cnpj string) (*dto.TenantDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCNPJ", ctx, cnpj)
	ret0, _ := ret[0].(*dto.TenantDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCNPJ indicates an expected call of GetByCNPJ.
func (mr *MockTenantServiceInterfaceMockRecorder) GetByCNPJ(ctx, cnpj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCNPJ", reflect.TypeOf((*MockTenantServiceInterface)(nil).GetByCNPJ), ctx, cnpj)
}

// GetByID mocks base method.
func (m *MockTenantServiceInterface) GetByID(ctx context.Context, id uint) (*dto.TenantDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.TenantDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTenantServiceInterfaceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTenantServiceInterface)(nil).GetByID), ctx, id)
}

// GetByTelefone mocks base method.
func (m *MockTenantServiceInterface) GetByTelefone(ctx context.Context, telefone string) (*dto.TenantDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTelefone", ctx, telefone)
	ret0, _ := ret[0].(*dto.TenantDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTelefone indicates an expected call of GetByTelefone.
func (mr *MockTenantServiceInterfaceMockRecorder) GetByTelefone(ctx, telefone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTelefone", reflect.TypeOf((*MockTenantServiceInterface)(nil).GetByTelefone), ctx, telefone)
}

// GetByVerifyToken mocks base method.
func (m *MockTenantServiceInterface) GetByVerifyToken(ctx context.Context, token string) (*dto.TenantDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByVerifyToken", ctx, token)
	ret0, _ := ret[0].(*dto.TenantDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByVerifyToken indicates an expected call of GetByVerifyToken.
func (mr *MockTenantServiceInterfaceMockRecorder) GetByVerifyToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByVerifyToken", reflect.TypeOf((*MockTenantServiceInterface)(nil).GetByVerifyToken), ctx, token)
}

// GetByWhatsAppPhoneID mocks base method.
func (m *MockTenantServiceInterface) GetByWhatsAppPhoneID(ctx context.Context, phoneID string) (*dto.TenantDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByWhatsAppPhoneID", ctx, phoneID)
	ret0, _ := ret[0].(*dto.TenantDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByWhatsAppPhoneID indicates an expected call of GetByWhatsAppPhoneID.
func (mr *MockTenantServiceInterfaceMockRecorder) GetByWhatsAppPhoneID(ctx, phoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByWhatsAppPhoneID", reflect.TypeOf((*MockTenantServiceInterface)(nil).GetByWhatsAppPhoneID), ctx, phoneID)
}

// GetPromptContext mocks base method.
func (m *MockTenantServiceInterface) GetPromptContext(ctx context.Context, tenantID uint) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromptContext", ctx, tenantID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPromptContext indicates an expected call of GetPromptContext.
func (mr *MockTenantServiceInterfaceMockRecorder) GetPromptContext(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromptContext", reflect.TypeOf((*MockTenantServiceInterface)(nil).GetPromptContext), ctx, tenantID)
}

// List mocks base method.
func (m *MockTenantServiceInterface) List(ctx context.Context) ([]dto.TenantDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]dto.TenantDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantServiceInterfaceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantServiceInterface)(nil).List), ctx)
}
