services:
  mcp-server:
    image: rafapasa/mcp-server:${IMAGE_TAG:-latest}
    container_name: mcp-server
    restart: unless-stopped
    networks:
      - mcp-network
    ports:
      - "8080:8080" # api + webhook juntos
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
      - GIN_MODE=release
    depends_on:
      - mysql
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # mysql e redis já vem do docker-compose.db.yml
  # não precisa duplicar aqui

networks:
  mcp-network:
    external: true