// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/rafapasa/mcp-server-openerp/internal/config"
	"github.com/rafapasa/mcp-server-openerp/internal/llm"
	"github.com/rafapasa/mcp-server-openerp/internal/observability/health"
	"github.com/rafapasa/mcp-server-openerp/internal/repository"
	"github.com/rafapasa/mcp-server-openerp/internal/server"
	"github.com/rafapasa/mcp-server-openerp/internal/service"
	"github.com/rafapasa/mcp-server-openerp/internal/webhook"
)

// Injectors from wire.go:

func InitializeApp() (*server.HttpServer, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	db := provideGormDB(configConfig)
	produtoRepository := repository.NewProdutoRepository(db)
	tenantRepository := repository.NewTenantRepository(db)
	redisInterface, err := provideRedis(configConfig)
	if err != nil {
		return nil, err
	}
	cardapioServiceInterface := service.NewCardapioService(produtoRepository, tenantRepository, redisInterface)
	pedidoRepository := repository.NewPedidoRepository(db)
	pedidoServiceInterface := service.NewPedidoService(pedidoRepository, cardapioServiceInterface)
	unifiedLLM := llm.NewUnifiedLLM(configConfig)
	llmServiceInterface := service.NewLLMService(unifiedLLM, cardapioServiceInterface)
	clienteRepositoryInterface := repository.NewClienteRepository(db)
	enderecoRepositoryInterface := repository.NewEnderecoRepository(db)
	clienteServiceInterface := service.NewClienteService(clienteRepositoryInterface, enderecoRepositoryInterface)
	carrinhoServiceInterface := service.NewCarrinhoService(redisInterface, cardapioServiceInterface, pedidoServiceInterface, produtoRepository, llmServiceInterface, clienteServiceInterface)
	mcpServer := server.NewMCPServer(configConfig, cardapioServiceInterface, pedidoServiceInterface, carrinhoServiceInterface, unifiedLLM)
	userRepositoryInterface := repository.NewUserRepository(db)
	authServiceInterface := service.NewAuthService(userRepositoryInterface, configConfig)
	apiHandlers := server.NewAPIHandlers(authServiceInterface, clienteServiceInterface, pedidoServiceInterface, cardapioServiceInterface)
	whatsAppClient := webhook.NewWhatsAppClient()
	tenantServiceInterface := service.NewTenantService(tenantRepository)
	processor := webhook.NewProcessor(whatsAppClient, tenantServiceInterface, clienteServiceInterface, carrinhoServiceInterface, redisInterface)
	webhookHandler := webhook.NewWebhookHandler(configConfig, processor)
	healthChecker := health.NewHealthChecker()
	httpServer := server.NewHttpServer(configConfig, mcpServer, apiHandlers, webhookHandler, healthChecker)
	return httpServer, nil
}

func InitializeMCPServer() (*server.MCPServer, error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, err
	}
	db := provideGormDB(configConfig)
	produtoRepository := repository.NewProdutoRepository(db)
	tenantRepository := repository.NewTenantRepository(db)
	redisInterface, err := provideRedis(configConfig)
	if err != nil {
		return nil, err
	}
	cardapioServiceInterface := service.NewCardapioService(produtoRepository, tenantRepository, redisInterface)
	pedidoRepository := repository.NewPedidoRepository(db)
	pedidoServiceInterface := service.NewPedidoService(pedidoRepository, cardapioServiceInterface)
	unifiedLLM := llm.NewUnifiedLLM(configConfig)
	llmServiceInterface := service.NewLLMService(unifiedLLM, cardapioServiceInterface)
	clienteRepositoryInterface := repository.NewClienteRepository(db)
	enderecoRepositoryInterface := repository.NewEnderecoRepository(db)
	clienteServiceInterface := service.NewClienteService(clienteRepositoryInterface, enderecoRepositoryInterface)
	carrinhoServiceInterface := service.NewCarrinhoService(redisInterface, cardapioServiceInterface, pedidoServiceInterface, produtoRepository, llmServiceInterface, clienteServiceInterface)
	mcpServer := server.NewMCPServer(configConfig, cardapioServiceInterface, pedidoServiceInterface, carrinhoServiceInterface, unifiedLLM)
	return mcpServer, nil
}
